Repository Activiti/activiti-core-common, pull requests merged in 2018-11, with the labels that each got.

#10 update org.activiti.api:activiti-api-dependencies to 7.0.38
  pom.xml
Labels: updatebot

#11 update org.activiti.api:activiti-api-dependencies to 7.0.39
  pom.xml
Labels: updatebot

#14 Create .mergify.yml
  .mergify.yml
Labels: enhancement, in progress

#12 update org.activiti.api:activiti-api-dependencies to 7.0.43
  pom.xml
Labels: in progress, updatebot

#18 update org.activiti.api:activiti-api-dependencies to 7.0.44
  pom.xml
Labels: in progress, updatebot

#16 fix: enable single pr into activiti-dependencies
  .updatebot.yml
Labels: enhancement, in progress

#19 update org.activiti.build:activiti-parent to 7.0.40
  pom.xml
Labels: in progress, updatebot

#22 update org.activiti.api:activiti-api-dependencies to 7.0.49
  pom.xml
Labels: in progress, updatebot

#23 update org.activiti.build:activiti-parent to 7.0.41
  pom.xml
Labels: in progress, ready-to-merge, updatebot

#24 update org.activiti.api:activiti-api-dependencies to 7.0.50
  pom.xml
Labels: in progress, updatebot

#26 update org.activiti.api:activiti-api-dependencies to 7.0.52
  pom.xml
Labels: in progress, updatebot

#27 fix: (updatebot) push version into activiti-core via singe pr
  .mergify.yml
  .updatebot.yml
  activiti-connector-model/pom.xml
  activiti-core-common-dependencies-tests/pom.xml
  activiti-core-common-dependencies/pom.xml
  activiti-spring-application/pom.xml
  activiti-spring-connector/pom.xml
  activiti-spring-identity/pom.xml
  activiti-spring-security-policies/pom.xml
  activiti-spring-security/pom.xml
  pom.xml
Labels: enhancement, in progress

#28 fix(versions): update Activiti/activiti-core-common versions
  pom.xml
Labels: in progress, updatebot

#29 fix(versions): update Activiti/activiti-core-common versions
  pom.xml
Labels: in progress, updatebot

#30 fix(versions): update Activiti/activiti-core-common versions
  pom.xml
Labels: in progress, updatebot

#31 fix(versions): update Activiti/activiti-core-common versions
  pom.xml
Labels: in progress, updatebot

#32 Automated tests for dependencies convergence in CI pipelines for Activiti Cloud
  .mergify.yml
  activiti-core-common-dependencies-tests/pom.xml
  activiti-core-common-dependencies/pom.xml
  pom.xml
Labels: enhancement, in progress

#33 fix(versions): update Activiti/activiti-core-common versions
  pom.xml
Labels: in progress, updatebot

#34 fix(versions): update Activiti/activiti-core-common versions
  pom.xml
Labels: in progress, updatebot
